[tool.ruff.lint]
select = [
    # Pyflakes
    "F", 
    # isort
    "I", 
    # pycodestyle -- warning
    "W", 
    # pep8-naming
    "N",
    # pydocstyle
    "D201", "D202",
    # flake8-quotes
    "Q",
    # flake8-comprehensions
    "C4",
    # flake8-unused-arguments
    "ARG",
    # flake8-annotations
    "ANN", 
    # flake8-builtins
    "A", 
    # flake8-pytest-style
    "PT",
]

ignore = [
    # missing-type-self
    "ANN101", 
    # missing-type-cls
    "ANN102",
    # missing-return-type-special-method
    "ANN204",
]

[tool.ruff]
line-length = 120
output-format = "grouped"

[tool.ruff.per-file-ignores]
"**/{tests,docs,tools}/*" = [
    # missing-return-type-undocumented-public-function
    "ANN201", 
    # missing-type-function-argument
    "ANN001", 
    # module-import-not-at-top-of-file
    "E402",
]

[tool.ruff.lint.isort]
# known-first-party = ["app"]
lines-after-imports = 2